[project]
name = "day1-yt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "coderharpuneet", email = "harpuneetsingh2006@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
]

[project.scripts]
day1-yt = "day1_yt:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
